# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Ubuntu 14.04
    config.vm.box = "box-cutter/ubuntu1404-desktop"

    # VirtualBox configs
    config.vm.provider "virtualbox" do |vb|
      # Show the VirtualBox GUI when booting the machine
      vb.gui = true

      vb.cpus = 2
      vb.memory = "2048"
      vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
      vb.customize ["modifyvm", :id, "--vram", "128"]
    end

    # Enable provisioning with a shell script.
    config.vm.provision "shell",
        path: "provision.sh"
end
