# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Ubuntu 14.04
    config.vm.box = "ubuntu/trusty64"

    # VirtualBox configs
    config.vm.provider "virtualbox" do |vb|
      # Show the VirtualBox GUI when booting the machine
      vb.gui = true

      # 1GB should be a good starting point for a dev machine
      vb.memory = "1024"
    end

    # Enable provisioning with a shell script. Additional provisioners such as
    # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
    # documentation for more information about their specific syntax and use.
    # config.vm.provision "shell", inline: <<-SHELL
    #   apt-get update
    #   apt-get install -y apache2
    # SHELL
end
